### ISSUE TITLE
Nextras Migrations

### ISSUE THREAD

**Issue by janpecha** [LeanMapper/examples#12]

**Comment by janpecha** [comment]
https://github.com/LeanMapper/examples/tree/master/nextras-migrations

**Comment by castamir** [comment]
diky, aspon moznost srovnani s https://github.com/Joseki/Migration, ktere pouzivam na svych projektech

**Comment by janpecha** [comment]
zajímavé, osobně pro generování migrací používám svůj https://github.com/inlm/schema-generator a Nextras Migrations používám vlastně jen pro jejich spouštění. Proto je i ten příklad hodně low-level - zatím jsem nepotřeboval jejich Nette DI rozšíření ani konzoli.
